// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmt4tM2BZ8e1jV-6IvDp1sTuMoVoW3lGw',
    appId: '1:359506011726:web:888becacaa42b3d391051f',
    messagingSenderId: '359506011726',
    projectId: 'vendor-bnb',
    authDomain: 'vendor-bnb.firebaseapp.com',
    storageBucket: 'vendor-bnb.firebasestorage.app',
    measurementId: 'G-EZW0EK6W83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GPux4Ja2requymmu9c2jQHm-yB6w6wM',
    appId: '1:359506011726:android:dea4433d541e0f7491051f',
    messagingSenderId: '359506011726',
    projectId: 'vendor-bnb',
    storageBucket: 'vendor-bnb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRkDwTUhy6XzecB8zJPzbPNEQW9jwymA',
    appId: '1:359506011726:ios:e685907eb00929bc91051f',
    messagingSenderId: '359506011726',
    projectId: 'vendor-bnb',
    storageBucket: 'vendor-bnb.firebasestorage.app',
    iosBundleId: 'com.vendor.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRkDwTUhy6XzecB8zJPzbPNEQW9jwymA',
    appId: '1:359506011726:ios:e685907eb00929bc91051f',
    messagingSenderId: '359506011726',
    projectId: 'vendor-bnb',
    storageBucket: 'vendor-bnb.firebasestorage.app',
    iosBundleId: 'com.vendor.vendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmt4tM2BZ8e1jV-6IvDp1sTuMoVoW3lGw',
    appId: '1:359506011726:web:4aa3b4142872bc7091051f',
    messagingSenderId: '359506011726',
    projectId: 'vendor-bnb',
    authDomain: 'vendor-bnb.firebaseapp.com',
    storageBucket: 'vendor-bnb.firebasestorage.app',
    measurementId: 'G-N9CFR08GBH',
  );
}
